export enum USCarBrand {
  Toyota = 'Toyota',
  Honda = 'Honda',
  Ford = 'Ford',
  Chevrolet = 'Chevrolet',
  Hyundai = 'Hyundai',
  Nissan = 'Nissan',
  Kia = 'Kia',
  Subaru = 'Subaru',
  Ram = 'Ram',
  Jeep = 'Jeep',
  GMC = 'GMC',
  BMW = 'BMW',
  MercedesBenz = 'Mercedes-Benz',
  Tesla = 'Tesla',
  Lexus = 'Lexus',
  Audi = 'Audi',
  Mazda = 'Mazda',
  Volkswagen = 'Volkswagen',
  Dodge = 'Dodge',
  Acura = 'Acura',
  Buick = 'Buick',
  Lincoln = 'Lincoln',
  Volvo = 'Volvo',
  Porsche = 'Porsche',
  Mini = 'Mini',
  LandRover = 'Land Rover',
  Infiniti = 'Infiniti',
  Cadillac = 'Cadillac',
  Genesis = 'Genesis',
  AlfaRomeo = 'Alfa Romeo'
}

export const carModels = {
  [USCarBrand.Toyota]: [
    'Camry',
    'Corolla',
    'Rav4',
    'Highlander',
    'Tacoma',
    'Prius',
    'Sienna',
    '4Runner',
    'Tundra',
    'Avalon',
    'C-HR',
    'Sequoia',
    'GR86',
    'Yaris'
  ],
  [USCarBrand.Honda]: [
    'Civic',
    'Accord',
    'CR-V',
    'Pilot',
    'Odyssey',
    'HR-V',
    'Ridgeline',
    'Passport',
    'Insight',
    'Clarity',
    'Fit',
    'S2000',
    'Element',
    'Prelude'
  ],
  [USCarBrand.Ford]: [
    'F-150',
    'Mustang',
    'Explorer',
    'Escape',
    'Bronco',
    'Ranger',
    'Edge',
    'Expedition',
    'Fusion',
    'Focus',
    'Transit',
    'Mach-E',
    'Maverick',
    'Taurus'
  ],
  [USCarBrand.Chevrolet]: [
    'Silverado',
    'Equinox',
    'Malibu',
    'Traverse',
    'Tahoe',
    'Suburban',
    'Camaro',
    'Corvette',
    'Colorado',
    'Trailblazer',
    'Blazer',
    'Bolt EV',
    'Impala',
    'Cruze'
  ],
  [USCarBrand.Hyundai]: [
    'Sonata',
    'Elantra',
    'Tucson',
    'Santa Fe',
    'Kona',
    'Palisade',
    'Accent',
    'Veloster',
    'Ioniq 5',
    'Venue',
    'Nexo',
    'Azera',
    'Genesis Coupe',
    'Equus'
  ],
  [USCarBrand.Nissan]: [
    'Altima',
    'Rogue',
    'Sentra',
    'Pathfinder',
    'Maxima',
    'Murano',
    'Frontier',
    'Armada',
    'Versa',
    'Leaf',
    'Z',
    'Kicks',
    'Titan',
    'Cube'
  ],
  [USCarBrand.Kia]: [
    'Sorento',
    'Sportage',
    'Forte',
    'Optima',
    'Telluride',
    'Soul',
    'Rio',
    'Sedona',
    'Stinger',
    'Niro',
    'K5',
    'Carnival',
    'EV6',
    'Cadenza'
  ],
  [USCarBrand.Subaru]: [
    'Outback',
    'Forester',
    'Impreza',
    'Crosstrek',
    'Legacy',
    'WRX',
    'Ascent',
    'BRZ',
    'Solterra',
    'Tribeca',
    'SVX',
    'Baja',
    'Justy',
    'XT'
  ],
  [USCarBrand.Ram]: [
    '1500',
    '2500',
    '3500',
    'Promaster',
    'Promaster City',
    'Dakota',
    '50',
    '100',
    '200',
    '300',
    '400',
    '500',
    '600',
    '700'
  ],
  [USCarBrand.Jeep]: [
    'Wrangler',
    'Grand Cherokee',
    'Cherokee',
    'Compass',
    'Renegade',
    'Gladiator',
    'Patriot',
    'Liberty',
    'Commander',
    'CJ',
    'Wagoneer',
    'Grand Wagoneer',
    'Comanche',
    'J10'
  ],
  [USCarBrand.GMC]: [
    'Sierra',
    'Yukon',
    'Terrain',
    'Acadia',
    'Canyon',
    'Savana',
    'Hummer EV',
    'Envoy',
    'Jimmy',
    'Sonoma',
    'Typhoon',
    'Syclone',
    'Rally Wagon',
    'Sprint'
  ],
  [USCarBrand.BMW]: [
    '3 Series',
    '5 Series',
    'X5',
    'X3',
    '7 Series',
    'M3',
    'M5',
    'X7',
    '4 Series',
    '2 Series',
    'X1',
    'Z4',
    '8 Series',
    'iX'
  ],
  [USCarBrand.MercedesBenz]: [
    'C-Class',
    'E-Class',
    'S-Class',
    'GLC',
    'GLE',
    'A-Class',
    'CLA',
    'GLA',
    'G-Class',
    'SL',
    'CLS',
    'GLS',
    'Metris',
    'Sprinter'
  ],
  [USCarBrand.Tesla]: [
    'Model S',
    'Model 3',
    'Model X',
    'Model Y',
    'Roadster',
    'Cybertruck',
    'Semi',
    'Model A',
    'Model B',
    'Model C',
    'Model D',
    'Model E',
    'Model F',
    'Model G'
  ],
  [USCarBrand.Lexus]: [
    'RX',
    'ES',
    'NX',
    'GX',
    'LX',
    'IS',
    'LS',
    'UX',
    'RC',
    'LC',
    'RZ',
    'CT',
    'SC',
    'HS'
  ],
  [USCarBrand.Audi]: [
    'A4',
    'A6',
    'Q5',
    'A3',
    'Q7',
    'A5',
    'Q3',
    'A7',
    'TT',
    'R8',
    'e-tron',
    'S4',
    'S5',
    'RS6'
  ],
  [USCarBrand.Mazda]: [
    'Mazda3',
    'CX-5',
    'Mazda6',
    'CX-9',
    'MX-5 Miata',
    'CX-30',
    'CX-50',
    'CX-3',
    'RX-8',
    'Tribute',
    'B-Series',
    'Millenia',
    'Protege',
    'MPV'
  ],
  [USCarBrand.Volkswagen]: [
    'Golf',
    'Jetta',
    'Passat',
    'Tiguan',
    'Atlas',
    'Taos',
    'Arteon',
    'ID.4',
    'Beetle',
    'GTI',
    'Touareg',
    'CC',
    'Phaeton',
    'Scirocco'
  ],
  [USCarBrand.Dodge]: [
    'Charger',
    'Challenger',
    'Durango',
    'Grand Caravan',
    'Journey',
    'Dart',
    'Viper',
    'Neon',
    'Intrepid',
    'Stealth',
    'Magnum',
    'Avenger',
    'Caliber',
    'Spirit'
  ],
  [USCarBrand.Acura]: [
    'MDX',
    'RDX',
    'TLX',
    'ILX',
    'Integra',
    'NSX',
    'RLX',
    'ZDX',
    'RSX',
    'Legend',
    'Vigor',
    'SLX',
    'CL',
    'EL'
  ],
  [USCarBrand.Buick]: [
    'Enclave',
    'Encore',
    'Envision',
    'LaCrosse',
    'Regal',
    'Verano',
    'Cascada',
    'LeSabre',
    'Park Avenue',
    'Riviera',
    'Skylark',
    'Century',
    'Roadmaster',
    'Reatta'
  ],
  [USCarBrand.Lincoln]: [
    'Navigator',
    'Aviator',
    'Corsair',
    'Nautilus',
    'Continental',
    'MKZ',
    'MKS',
    'MKT',
    'LS',
    'Town Car',
    'Mark LT',
    'Blackwood',
    'Zephyr',
    'Versailles'
  ],
  [USCarBrand.Volvo]: [
    'XC90',
    'XC60',
    'S60',
    'V60',
    'S90',
    'V90',
    'C40',
    'XC40',
    'S40',
    'V50',
    'C30',
    '740',
    '850',
    '960'
  ],
  [USCarBrand.Porsche]: [
    '911',
    'Cayenne',
    'Macan',
    'Panamera',
    'Taycan',
    '718 Cayman',
    '718 Boxster',
    '928',
    '944',
    '968',
    'Carrera GT',
    '959',
    '356',
    '914'
  ],
  [USCarBrand.Mini]: [
    'Cooper',
    'Countryman',
    'Clubman',
    'Convertible',
    'Hardtop 2 Door',
    'Hardtop 4 Door',
    'Paceman',
    'Roadster',
    'Coupe',
    'John Cooper Works',
    'Electric',
    'Moke',
    'Traveller',
    'Riley Elf'
  ],
  [USCarBrand.LandRover]: [
    'Range Rover',
    'Discovery',
    'Defender',
    'Range Rover Sport',
    'Range Rover Evoque',
    'Discovery Sport',
    'Freelander',
    'Series',
    'Velar',
    'LR2',
    'LR3',
    'LR4',
    'Forward Control',
    '101'
  ],
  [USCarBrand.Infiniti]: [
    'QX60',
    'QX50',
    'QX80',
    'Q50',
    'Q60',
    'Q70',
    'EX35',
    'FX35',
    'JX35',
    'G35',
    'G37',
    'I30',
    'J30',
    'M30'
  ],
  [USCarBrand.Cadillac]: [
    'Escalade',
    'XT5',
    'XT4',
    'CT5',
    'CT6',
    'CT4',
    'Lyriq',
    'ATS',
    'CTS',
    'DTS',
    'XLR',
    'Seville',
    'DeVille',
    'Eldorado'
  ],
  [USCarBrand.Genesis]: [
    'G70',
    'G80',
    'G90',
    'GV70',
    'GV80',
    'Electrified G80',
    'Electrified GV70',
    'X Concept',
    'Essentia',
    'Mint',
    'Neolun',
    'GV60',
    'X Speedium Coupe',
    'X Gran Berlinetta'
  ],
  [USCarBrand.AlfaRomeo]: [
    'Giulia',
    'Stelvio',
    '4C',
    'Giulietta',
    'Spider',
    'Tonale',
    '8C Competizione',
    'Brera',
    '159',
    '156',
    '147',
    'GTV6',
    'Alfetta',
    'Montreal'
  ]
};
